language: cpp
sudo: required

before_install:
  - if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then sudo apt-get update -qq; fi
  - if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then sudo apt-get install -y cmake libfreetype6-dev libharfbuzz-dev libfribidi-dev libcairo2-dev libfmt-dev; fi
  - if [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then brew update; fi
  - if [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then brew install freetype harfbuzz fribidi cairo cppformat; fi

script:
  - cmake .
  - make all

jobs:
  include:
    - os: linux
      dist: bionic
      compiler: gcc
    - os: linux
      dist: bionic
      compiler: clang
    - os: osx
      osx_image: xcode9.4
    - os: osx
      osx_image: xcode11
